---
title: "Planetscope time series"
author: "Zhehan"
date: "January 30, 2019"
output: html_document
---
#package 
```{r}
library(XML)
library(plyr)
library(qdapRegex)
library(raster)
library(dplyr)
```

#read shapefiles 
##Russell Ranch shapefiles
```{r}

#path_shp <- "Z:/CC_UCD_atRR/data2/BNDs"
path_shp <- "/z0/zt92/CC_UCD_RR_2019/2019/shapefiles"
#a small area that just covers RR
RR_BND <- shapefile(file.path(path_shp, "RR_BND_sen2.shp"))
#plot(RR_BND_sen2, add= TRUE)

#The shapefile of the center of each field with a 15m buffer 
Cen5_buff <- shapefile(file.path(path_shp, "RR_center_15mbuffer_5tomato_2019.shp"))
#plot(RR_center, add = TRUE)
Cen15_buff <- shapefile(file.path(path_shp, "RR_center_15mbuffer_15tomato_2019.shp"))


```
##Meerae's tomato field shapefiles
```{r}
#large boundary
MRtomato_BND <- shapefile(file.path(path_shp, "MR_tomatoBND_2019.shp"))
#inner buffer from the large boundary
MRtomato_BNDbuff <- shapefile(file.path(path_shp, "MR_tomatoBND_2019_buff.shp"))

```


#read metadata 
```{r}
#path_pl <- "Z:/CC_UCD_atRR/data1/Planetscope"
path_pl <- "/z0/zt92/CC_UCD_RR_2019/Planetscope"
#list of all metadata files 
plmeta_ls <- as.list(list.files(path_pl, pattern = "xml"))

plmeta_dates <- sapply(plmeta_ls, function(x){qdapRegex::rm_between(x, "_", "_", extract = TRUE)[[1]][2]})

#empty list to store all metadata
pl_meta <- list()
for(i in 1:length(plmeta_ls)){
  #metadata 
  meta <- XML::xmlParse(file.path(path_pl, plmeta_ls[[i]]))
  metatop <- XML::xmlRoot(meta)
  #read the conversion coefficient from metadata
  pl_meta[[i]] <- c(as.numeric(xmlValue(metatop[[5]][[1]][[6]][[5]][[1]])),  as.numeric(xmlValue(metatop[[5]][[1]][[7]][[5]][[1]])),  as.numeric(xmlValue(metatop[[5]][[1]][[8]][[5]][[1]])),  as.numeric(xmlValue(metatop[[5]][[1]][[9]][[5]][[1]])))
  #give it a name 
  names(pl_meta)[i] <- qdapRegex::rm_between(plmeta_ls[[i]], "_", "_", extract = TRUE)[[1]][2]
  #print the date for checking purpose 
  print(names(pl_meta)[i])
}


```

#read image file, extract values and crop to a smaller region 
##5 tomato fields in the center of RR 2019
```{r}
#list of all image files 
pl_ls <- as.list(list.files(path_pl, pattern = ".tif"))
pl_ls <- setdiff(pl_ls, plmeta_ls)
#get dates 
pl_dates <- sapply(pl_ls, function(x){qdapRegex::rm_between(x, "_", "_", extract = TRUE)[[1]][2]})

#empty list to store all image data
path_plsb <- "/z0/zt92/CC_UCD_RR_2019/Planetscope/RR_subset"
pl_img <- list()

Cen5mean_PL <- data.frame()
start_time <- Sys.time()
for(i in 1:length(pl_ls)){
  #read files
  img <- raster::brick(file.path(path_pl, pl_ls[[i]]))
  
  #crop to a small area
  img_crop <- raster::crop(img, RR_BND)
  
  #write the raster
  #writeRaster(img_crop, file.path(path_plsb, paste("PL",pl_dates[[1]],"RR.tif",sep = "_")))
  writeRaster(img_crop, file.path(path_plsb, paste(pl_ls[[i]], "RR.tif", sep = "_")))
  
  #extract the reflectance of each band for 5 fields
  img_ext <- raster::extract(img_crop, Cen5_buff, na.rm = TRUE, buffer = 0, df = TRUE, fun = mean)
  names(img_ext) <- c("Field","B1","B2","B3","B4")
  img_ext$Field <- Cen5_buff$FieldID
  
  #multiply by the coefficient
  img_ext$B1 <- img_ext$B1 * pl_meta[[i]][1]
  img_ext$B2 <- img_ext$B2 * pl_meta[[i]][2]
  img_ext$B3 <- img_ext$B3 * pl_meta[[i]][3]
  img_ext$B4 <- img_ext$B4 * pl_meta[[i]][4]
  
  #add dates to the data frame
  img_ext$Date <- as.Date(pl_dates[i])
  #add file names 
  img_ext$Filename <- pl_ls[[i]]
  
  #add the data frame to the exiting data frame 
  Cen5mean_PL <- rbind(Cen5mean_PL, img_ext)
  
  #print the dates 
  print(pl_ls[[i]])
}
end_time <- Sys.time()
end_time - start_time

path_output <- "/z0/zt92/CC_UCD_RR_2019/Outputs"
write.csv(Cen5mean_PL, file.path(path_output, "Cen5mean_PL.csv"), row.names = FALSE)

```

##15 tomato fields in RR 2019
no need to crop again 
```{r}
#list of all image files 
pl_ls <- as.list(list.files(path_pl, pattern = ".tif"))
pl_ls <- setdiff(pl_ls, plmeta_ls)
#get dates 
pl_dates <- sapply(pl_ls, function(x){qdapRegex::rm_between(x, "_", "_", extract = TRUE)[[1]][2]})

#empty list to store all image data
path_plsb <- "/z0/zt92/CC_UCD_RR_2019/Planetscope/RR_subset"
pl_img <- list()

Cen15mean_PL <- data.frame()
start_time <- Sys.time()
for(i in 1:length(pl_ls)){
  #read files
  img <- raster::brick(file.path(path_pl, pl_ls[[i]]))


  #extract the reflectance of each band for 5 fields
  img_ext <- raster::extract(img, Cen15_buff, na.rm = TRUE, buffer = 0, df = TRUE, fun = mean)
  names(img_ext) <- c("Field","B1","B2","B3","B4")
  img_ext$Field <- Cen15_buff$FieldID
  
  #multiply by the coefficient
  img_ext$B1 <- img_ext$B1 * pl_meta[[i]][1]
  img_ext$B2 <- img_ext$B2 * pl_meta[[i]][2]
  img_ext$B3 <- img_ext$B3 * pl_meta[[i]][3]
  img_ext$B4 <- img_ext$B4 * pl_meta[[i]][4]
  
  #add dates to the data frame
  img_ext$Date <- as.Date(pl_dates[i])
  #add file names 
  img_ext$Filename <- pl_ls[[i]]
  
  #add the data frame to the exiting data frame 
  Cen15mean_PL <- rbind(Cen15mean_PL, img_ext)
  
  #print the dates 
  print(pl_ls[[i]])
}
end_time <- Sys.time()
end_time - start_time


path_outputs <- "/z0/zt92/CC_UCD_RR_2019/Outputs"
write.csv(Cen15mean_PL, file.path(path_outputs, "Cen15mean_PL.csv"), row.names = FALSE)

```

##Meerae's field in 2019
They are in the same Planetscope image, I assume? 
```{r}
#list of all image files 
pl_ls <- as.list(list.files(path_pl, pattern = ".tif"))
pl_ls <- setdiff(pl_ls, plmeta_ls)
#get dates 
pl_dates <- sapply(pl_ls, function(x){qdapRegex::rm_between(x, "_", "_", extract = TRUE)[[1]][2]})

#empty list to store all image data
path_plsb_MR <- "/z0/zt92/CC_UCD_RR_2019/Planetscope/MR_subset"
pl_img <- list()

MRmean_PL <- data.frame()
start_time <- Sys.time()
for(i in 1:length(pl_ls)){
  #read files
  img <- raster::brick(file.path(path_pl, pl_ls[[i]]))
  
  #crop to a small area
  img_crop <- raster::crop(img, MRtomato_BND)
  
  #write the raster
  writeRaster(img_crop, file.path(path_plsb_MR, paste(pl_ls[[i]], "MR.tif", sep = "_")))

  
  #extract the reflectance of each band for 5 fields
  img_ext <- raster::extract(img_crop, MRtomato_BNDbuff, na.rm = TRUE, buffer = 0, df = TRUE, fun = mean)
  names(img_ext) <- c("ID", "B1", "B2", "B3", "B4")
  #names(img_ext) <- c("Field","B1","B2","B3","B4")
  #img_ext$Field <- Cen5_buff$FieldID
  
  #multiply by the coefficient
  img_ext$B1 <- img_ext$B1 * pl_meta[[i]][1]
  img_ext$B2 <- img_ext$B2 * pl_meta[[i]][2]
  img_ext$B3 <- img_ext$B3 * pl_meta[[i]][3]
  img_ext$B4 <- img_ext$B4 * pl_meta[[i]][4]
  
  #add dates to the data frame
  img_ext$Date <- as.Date(pl_dates[i])
  #add file names to the data frame 
  img_ext$Filename <- pl_ls[[i]]
  
  #add the data frame to the exiting data frame 
  MRmean_PL <- rbind(MRmean_PL, img_ext)

  #print the dates 
  print(pl_ls[[i]])
}
end_time <- Sys.time()
end_time - start_time

path_outputs <- "/z0/zt92/CC_UCD_RR_2019/Outputs"
write.csv(MRmean_PL, file.path(path_outputs, "MRmean_PL.csv"), row.names = FALSE)

```












```{r}
for(i in 1:length(pl_ls)){
  #read the image 
  img <- raster::brick(file.path(path_pl, pl_ls[[i]]))
  
  #crop with the boundary shapefile 
  pl_img[[i]] <- raster::crop(img, RR_BND_sen2)
  
  #calculate with the conversion coefficient 
  ##Blue
  pl_img[[i]][[1]] = pl_img[[i]][[1]]*pl_meta[[i]][1]
  ##green
  pl_img[[i]][[2]] = pl_img[[i]][[2]]*pl_meta[[i]][2]
  ##red 
  pl_img[[i]][[3]] = pl_img[[i]][[3]]*pl_meta[[i]][3]
  ##nir
  pl_img[[i]][[4]] = pl_img[[i]][[4]]*pl_meta[[i]][4]
  
  #give each a name 
  names(pl_img)[i] <- qdapRegex::rm_between(pl_ls[[i]], "_", "_", extract = TRUE)[[1]][2]
  #print the date for checking purpose 
  print(names(pl_img)[i])
}
end_time <- Sys.time()
end_time - start_time

```

