---
title: "Yield_Prediction_RR"
author: "Zhehan"
date: "November 11, 2019"
output: html_document
---
#Package
```{r}
library(raster)
library(dplyr)
library(readxl)
library(ggplot2)
```

#Multi-year field data 
```{r}
path_yield <- "Z:/CC_UCD_atRR/data2/GIS"
tomall9419 <- read.csv(file.path(path_yield,"tomato_yld_geospat_1994_2019 (20191112).csv"))
head(tomall9419)
tomall9419$cash_crop_planned <- NULL
tomall9419$cash_crop_planted <- NULL
names(tomall9419)[7:11] <- c("plant_date","harv_date","yield","greenDM","vineDM")

#change class
str(tomall9419)
tomall9419$plant_date <- as.Date(as.character(tomall9419$plant_date),"%m/%d/%Y")
tomall9419$harv_date <- as.Date(as.character(tomall9419$harv_date),"%m/%d/%Y")
tomall9419$block <- as.factor(tomall9419$block)

#only the yield matters 
tomyld9419 <- tomall9419[,c(1:9)]
tomyld9419 <- na.omit(tomyld9419)

#aggregate to the plot 
tomyld9419_plotagg <- aggregate(tomyld9419$yield, by = list(tomyld9419$year, tomyld9419$plot_code, tomyld9419$block, tomyld9419$system_code, tomyld9419$irrigation, tomyld9419$plant_date, tomyld9419$harv_date), mean)
head(tomyld9419_plotagg)
names(tomyld9419_plotagg) <- c("year","plot_code","block","system_code","irrigation","plant_date","harv_date","yield")
#include the DM
tomall9419_cl <- na.omit(tomall9419)
names(tomall9419_cl)
tomall9419_cl_plotagg <- aggregate(tomall9419_cl[,9:11], by = list(tomall9419_cl$year, tomall9419_cl$plot_code, tomall9419_cl$block, tomall9419_cl$system_code, tomall9419_cl$irrigation, tomall9419_cl$plant_date, tomall9419_cl$harv_date), mean)
names(tomall9419_cl_plotagg)[1:7] <- c("year","plot_code","block","system_code","irrigation","plant_date","harv_date")
#remove all data that have greenDM in 2017 and 2018
tomall9417_cl <- subset(tomall9419_cl, year!=2018 & year!=2017)
```


#Exploratory Plots
##Yield vs system_code
```{r}
#without plot aggregation
ggplot(tomyld9419, aes(x = system_code, y = yield, col = system_code)) + geom_boxplot() + 
ggplot(tomall9417, aes(y = yield, x = system_code, col = system_code)) + geom_boxplot()

ggplot(tomall9417_plotagg, aes(x = system_code, y = yield)) + geom_boxplot()
```

##Harvest Index
```{r}
ggplot(tomall9417_cl, aes(x = greenDM, y = yield, col = system_code)) + geom_point() + geom_smooth(method = lm, se = FALSE)


cor(tomall9417_cl$greenDM, tomall9417_cl$yield)^2
cor(tomall9417_cl$vineDM, tomall9417_cl$yield)^2

tomall1317 <- subset(tomall9417_cl, year>2013 & year < 2017)
cor(tomall1317$yield, tomall1317$greenDM)^2
cor(tomall1317$yield, tomall1317$vineDM)^2

a <- split(tomall9417_cl, tomall9417_cl$system_code)
sapply(a, function(x){cor(x$greenDM, x$yield)^2})
sapply(a, function(x){cor(x$vineDM, x$yield)^2})
sapply(a, function(x){cor(x$greenDM+x$vineDM, x$yield)^2})

```

